In [2]:
import pandas as pd

df = pd.read_parquet("data/processed/foods_master.parquet")

df.head()

,food_id,food_name_en,food_name_ar,food_group,meal_types,serving_name,serving_weight_g,nutrition_basis,calories,protein,carbs,fat,fiber,diet_tags,allergens,is_composite_dish,source
0,egy_5b14dcd94b29,almonds,,Healthy Fats,Lunch|Dinner,100 g,100.0,per_100g,640.0,9.3,15.1,44.9,1.5,plant_based,,False,egyptian_food
1,egy_76c2436b593f,apples,,Fruits,Snack,100 g,100.0,per_100g,57.0,0.4,13.5,0.2,0.8,plant_based,,False,egyptian_food
2,egy_97648380db29,apricots,,Fruits,Snack,100 g,100.0,per_100g,58.0,0.9,12.7,0.4,0.7,plant_based,,False,egyptian_food
3,egy_bace40a1320f,"apricots, dried",,Fruits,Snack,100 g,100.0,per_100g,282.0,4.5,64.6,0.6,3.2,plant_based,,False,egyptian_food
4,egy_c57a56bb0791,artichokes,,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,45.0,3.5,7.4,0.2,2.0,plant_based,,False,egyptian_food

In [3]:
df

,food_id,food_name_en,food_name_ar,food_group,meal_types,serving_name,serving_weight_g,nutrition_basis,calories,protein,carbs,fat,fiber,diet_tags,allergens,is_composite_dish,source
0,egy_5b14dcd94b29,almonds,,Healthy Fats,Lunch|Dinner,100 g,100.0,per_100g,640.0000,9.300000,15.100000,44.9000,1.5,plant_based,,False,egyptian_food
1,egy_76c2436b593f,apples,,Fruits,Snack,100 g,100.0,per_100g,57.0000,0.400000,13.500000,0.2000,0.8,plant_based,,False,egyptian_food
2,egy_97648380db29,apricots,,Fruits,Snack,100 g,100.0,per_100g,58.0000,0.900000,12.700000,0.4000,0.7,plant_based,,False,egyptian_food
3,egy_bace40a1320f,"apricots, dried",,Fruits,Snack,100 g,100.0,per_100g,282.0000,4.500000,64.600000,0.6000,3.2,plant_based,,False,egyptian_food
4,egy_c57a56bb0791,artichokes,,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,45.0000,3.500000,7.400000,0.2000,2.0,plant_based,,False,egyptian_food
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,usda_596fb7a8df47,"yogurt, greek, plain, nonfat",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,61.0000,10.300000,3.640000,0.3700,0.0,animal_based,milk,False,usda_foundation
835,usda_dc151a7847a1,"yogurt, greek, plain, whole milk",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,93.6776,8.778880,4.754020,4.3940,0.0,animal_based,milk,False,usda_foundation
836,usda_6a1ef03a8cfb,"yogurt, greek, strawberry, nonfat",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,83.0000,8.060000,12.200000,0.1500,0.6,animal_based,milk,False,usda_foundation
837,usda_4fa28c373d56,"yogurt, plain, nonfat",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,50.0015,4.226750,8.076750,0.0875,0.0,animal_based,milk,False,usda_foundation
838,usda_166825a7c973,"yogurt, plain, whole milk",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,77.9524,3.824172,5.574928,4.4840,0.0,animal_based,milk,False,usda_foundation

In [4]:
df.shape

(839, 17)

In [5]:
df.columns

Index(['food_id', 'food_name_en', 'food_name_ar', 'food_group', 'meal_types',
       'serving_name', 'serving_weight_g', 'nutrition_basis', 'calories',
       'protein', 'carbs', 'fat', 'fiber', 'diet_tags', 'allergens',
       'is_composite_dish', 'source'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 839 entries, 0 to 838
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   food_id            839 non-null    object
 1   food_name_en       839 non-null    object
 2   food_name_ar       839 non-null    object
 3   food_group         839 non-null    object
 4   meal_types         839 non-null    object
 5   serving_name       839 non-null    object
 6   serving_weight_g   839 non-null    float64
 7   nutrition_basis    839 non-null    object
 8   calories           839 non-null    float64
 9   protein            839 non-null    float64
 10  carbs              839 non-null    float64
 11  fat                839 non-null    float64
 12  fiber              839 non-null    float64
 13  diet_tags          839 non-null    object
 14  allergens          839 non-null    object
 15  is_composite_dish  839 non-null    bool
 16  source             839 non-null    object
dtypes: bool(1), float64(6), object(10)
memory usage: 105.8+ KB

In [9]:
df.head(30)

,food_id,food_name_en,food_name_ar,food_group,meal_types,serving_name,serving_weight_g,nutrition_basis,calories,protein,carbs,fat,fiber,diet_tags,allergens,is_composite_dish,source
0,egy_5b14dcd94b29,almonds,,Healthy Fats,Lunch|Dinner,100 g,100.0,per_100g,640.0,9.3,15.1,44.9,1.5,plant_based,,False,egyptian_food
1,egy_76c2436b593f,apples,,Fruits,Snack,100 g,100.0,per_100g,57.0,0.4,13.5,0.2,0.8,plant_based,,False,egyptian_food
2,egy_97648380db29,apricots,,Fruits,Snack,100 g,100.0,per_100g,58.0,0.9,12.7,0.4,0.7,plant_based,,False,egyptian_food
3,egy_bace40a1320f,"apricots, dried",,Fruits,Snack,100 g,100.0,per_100g,282.0,4.5,64.6,0.6,3.2,plant_based,,False,egyptian_food
4,egy_c57a56bb0791,artichokes,,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,45.0,3.5,7.4,0.2,2.0,plant_based,,False,egyptian_food
5,egy_7e30fcde415c,"artichokes, salad",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,89.0,2.7,9.0,4.7,1.4,plant_based,,False,egyptian_food
6,egy_fdb7388828a7,avocado,,Healthy Fats,Lunch|Dinner,100 g,100.0,per_100g,165.0,2.2,7.5,14.0,1.5,plant_based,,False,egyptian_food
7,egy_a0a620f514d3,backing powder,,Composite Dish,Lunch|Dinner,100 g,100.0,per_100g,144.0,0.9,35.0,5.8,0.8,composite,,False,egyptian_food
8,egy_d13218f1b0f9,bananas,,Fruits,Snack,100 g,100.0,per_100g,95.0,1.3,21.7,0.3,0.6,plant_based,,False,egyptian_food
9,egy_33edbb265388,"barley, grains",شعير,Grains,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,335.0,10.7,69.6,1.5,6.9,plant_based,,False,egyptian_food
10,egy_eb0fbdf8124a,"beans, broad",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,326.0,24.1,54.0,1.5,6.9,plant_based,,False,egyptian_food
11,egy_336134b2a5b0,"beans, broad (bisara)",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,130.0,6.0,17.4,4.0,3.3,plant_based,,False,egyptian_food
12,egy_e7961a2674ef,"beans, broad (foul), canned",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,132.0,6.1,15.7,5.0,2.1,plant_based,,False,egyptian_food
13,egy_270a99ee3c40,"beans, broad (foulmedames)",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,98.0,5.6,17.2,0.7,2.0,plant_based,,False,egyptian_food
14,egy_41e7808b9cd2,"beans, broad (green)",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,79.0,5.7,13.2,0.4,2.4,plant_based,,False,egyptian_food
15,egy_c85bf2e06bae,"beans, broad (menabet)",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,145.0,10.4,24.2,0.7,2.9,plant_based,,False,egyptian_food
16,egy_64b80bbd4c9c,"beans, broad (nabet)cooked",مطبوخ,Composite Dish,Lunch|Dinner,100 g,100.0,per_100g,114.0,8.8,18.4,0.6,1.0,composite,,True,egyptian_food
17,egy_0641f83c4dd1,"beans, broad (taamia), fride",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,355.0,10.9,32.6,20.1,1.5,plant_based,,False,egyptian_food
18,egy_ea1655b0853b,"beans, broad, decorticated",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,346.0,25.9,56.2,2.0,2.8,plant_based,,False,egyptian_food
19,egy_102743ead69e,"beans, green",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,30.0,1.8,5.2,0.2,1.1,plant_based,,False,egyptian_food
20,egy_87b73560b819,"beans, green, cooked",مطبوخ,Composite Dish,Lunch|Dinner,100 g,100.0,per_100g,61.0,1.9,6.2,3.2,1.1,composite,,True,egyptian_food
21,egy_12d237f956d8,"beans, kidey (red)",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,323.0,23.1,54.8,1.3,5.8,plant_based,,False,egyptian_food
22,egy_73a930ee1a11,"beans, kidey (white)",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,333.0,22.1,58.0,1.4,4.2,plant_based,,False,egyptian_food
23,egy_d14d40a29366,"beans, kidey white with meat",مع لحمة,Composite Dish,Lunch|Dinner,100 g,100.0,per_100g,152.0,11.4,14.0,5.6,2.0,composite,,True,egyptian_food
24,egy_f3356bb26108,"beans, kidey white, cooked",مطبوخ,Composite Dish,Lunch|Dinner,100 g,100.0,per_100g,134.0,8.9,19.3,2.4,1.9,composite,,True,egyptian_food
25,egy_d2e6397fb3f9,"beans, mung",,Legumes,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,352.0,21.4,62.1,2.0,4.0,plant_based,,False,egyptian_food
26,egy_dcefd2888062,beef meat (brown sause),لحم بقري لحمة,Protein,Lunch|Dinner,100 g,100.0,per_100g,159.0,14.0,0.9,11.0,0.3,animal_based,,False,egyptian_food
27,egy_f7aef9dade71,"beef, basterma",لحم بقري,Protein,Lunch|Dinner,100 g,100.0,per_100g,201.0,28.6,8.5,5.8,1.5,animal_based,,False,egyptian_food
28,egy_a71bda07e759,"beef, basterma meat",لحم بقري لحمة,Protein,Lunch|Dinner,100 g,100.0,per_100g,29.9,4.0,0.5,7.5,0.0,animal_based,,False,egyptian_food
29,egy_a3a845bf91c3,"beef, brain",لحم بقري,Protein,Lunch|Dinner,100 g,100.0,per_100g,121.0,10.4,0.6,8.5,0.0,animal_based,,False,egyptian_food

In [8]:
df.tail(20)

,food_id,food_name_en,food_name_ar,food_group,meal_types,serving_name,serving_weight_g,nutrition_basis,calories,protein,carbs,fat,fiber,diet_tags,allergens,is_composite_dish,source
819,usda_b1d943462b00,"tomato, paste, canned, without salt added",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,104.2825,4.234375,20.188125,0.7325,4.7040,plant_based,,False,usda_foundation
820,usda_66bfdb3d8208,"tomato, puree, canned",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,40.8450,1.578125,8.036875,0.2650,1.9710,plant_based,,False,usda_foundation
821,usda_eaed46648ff6,"tomato, roma",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,21.9574,0.695625,3.837475,0.4250,0.9706,plant_based,,False,usda_foundation
822,usda_39e99b9bc7a6,"tomato, sauce, canned, with salt added",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,34.1765,1.351875,6.331625,0.3825,1.6360,plant_based,,True,usda_foundation
823,usda_3aec263ce758,"tomatoes, canned, red, ripe, diced",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,18.0000,0.840000,3.320000,0.5000,0.0000,plant_based,,False,usda_foundation
824,usda_861e2f7b8975,"tomatoes, crushed, canned",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,37.8755,1.437500,7.137000,0.3975,1.9440,plant_based,,False,usda_foundation
825,usda_3b590154b3f0,"tomatoes, grape, raw",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,27.0000,0.830000,5.510000,0.6300,2.1000,plant_based,,False,usda_foundation
826,usda_780828ff5c4c,"tomatoes, whole, canned, solids and liquids, w...",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,22.4763,0.867500,4.287400,0.2063,0.8725,plant_based,,True,usda_foundation
827,usda_9ac324caf26a,"tuna, ahi or yellowfin, frozen, wild caught",,Protein,Lunch|Dinner,100 g,100.0,per_100g,101.8695,24.700000,0.000000,0.3875,0.0000,animal_based,fish,False,usda_foundation
828,usda_3ef834058237,"turkey, ground, 93% lean, 7% fat, pan-broiled ...",,Protein,Lunch|Dinner,100 g,100.0,per_100g,220.0000,27.100000,0.000000,11.6000,0.0000,animal_based,,False,usda_foundation
829,usda_637a5b3bcfc9,"turkey, ground, 93% lean/ 7% fat, raw",,Protein,Lunch|Dinner,100 g,100.0,per_100g,152.6150,17.343750,0.000000,9.5910,0.0000,animal_based,,False,usda_foundation
830,usda_5a7587421c77,"turnips, raw",,Vegetables,Lunch|Dinner,100 g,100.0,per_100g,33.9816,0.953125,7.274975,0.1188,1.9150,plant_based,,False,usda_foundation
831,usda_a2e7767c0c3a,"watermelon, seedless, flesh only, raw",,Fruits,Snack,100 g,100.0,per_100g,0.0000,0.871250,0.000000,0.0000,0.0000,plant_based,,False,usda_foundation
832,usda_a00c12ff977d,"watermelon, seedless, rind only, raw",,Fruits,Snack,100 g,100.0,per_100g,19.4190,0.531250,4.166000,0.0700,1.5350,plant_based,,False,usda_foundation
833,usda_f53bb734fe6e,"wild rice, dry, raw",,Grains,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,369.1640,12.787500,75.669500,1.7040,4.2600,plant_based,,False,usda_foundation
834,usda_596fb7a8df47,"yogurt, greek, plain, nonfat",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,61.0000,10.300000,3.640000,0.3700,0.0000,animal_based,milk,False,usda_foundation
835,usda_dc151a7847a1,"yogurt, greek, plain, whole milk",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,93.6776,8.778880,4.754020,4.3940,0.0000,animal_based,milk,False,usda_foundation
836,usda_6a1ef03a8cfb,"yogurt, greek, strawberry, nonfat",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,83.0000,8.060000,12.200000,0.1500,0.6000,animal_based,milk,False,usda_foundation
837,usda_4fa28c373d56,"yogurt, plain, nonfat",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,50.0015,4.226750,8.076750,0.0875,0.0000,animal_based,milk,False,usda_foundation
838,usda_166825a7c973,"yogurt, plain, whole milk",,Dairy,Breakfast|Lunch|Dinner,100 g,100.0,per_100g,77.9524,3.824172,5.574928,4.4840,0.0000,animal_based,milk,False,usda_foundation